---

- name: set system hostname
  hostname:
    name='{{ hostname }}'

- name: set 127.0.1.1 entry in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ hostname }} '
    state: present
