---

# Installing the SSH key on the backup server is a critical administrative task and
# is outside the scope of this automation.
- name: generate ssh key for root user and display public key, required for connecting to backup server
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    ssh_key_comment: ansible-generated on {{ hostname }}
  register: root_ssh_public_key

- name: get root ssh public key
  command: cat /root/.ssh/id_rsa.pub
  register: root_ssh_public_key
  changed_when: false

- name: show root ssh public key
  debug: var=root_ssh_public_key.stdout
