---

- name: upgrade all packages to the latest version
  apt:
    upgrade: yes
    force_apt_get: yes
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_seconds }}"

- name: remove dependencies that are no longer required
  apt:
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_seconds }}"
    autoremove: yes
