---

- name: install convenience and debugging packages using apt
  apt:
    name={{ item }}
    state=present
    update_cache=yes
    cache_valid_time="{{ apt_cache_valid_time_seconds }}"
  with_items:
    - emacs
    - iftop
    - traceroute
    - nmap
    - lft
