---

- name: create webroot directory for letsencrypt challenges
  file:
    path: /var/www/letsencrypt/
    state: directory
    recurse: yes
    owner: root
    group: nginx
    mode: 0750

- name: install software-properties-common (ppa dependency)
  apt:
    name: software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_seconds }}"

- name: add apt ppa required for certbot
  apt_repository:
    repo: 'ppa:certbot/certbot'

- name: install certbot
  apt:
    name: certbot
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time_seconds }}"

# Runs using letsencrypt's "deploy_hook" functionality, to reload nginx
- name: copy certificate installation script
  template:
    src: nginx_letsencrypt_deploy_hook.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/deploy/nginx_letsencrypt_deploy_hook.sh
    owner: root
    group: root
    mode: 0500

# Helper script in case we need to debug certificates, allows easy purging of certificate from letsencrypt dir.
- name: copy purge certificate utility script for debugging
  template:
    src: purge_certificates.sh.j2
    dest: /root/purge_certificates.sh
    owner: root
    group: root
    mode: 0500
