---

- name: restart unifi controller
  service:
    name: unifi
    state: restarted
  notify:
    - wait for unifi controller to be healthy

- name: wait for unifi controller to be healthy
  wait_for:
    timeout: 1
    port: 8443
  register: result
  until: result is succeeded
  retries: 60
  delay: 1
