---
# Playbook to perform all system updates, to be run periodically.

- name: Apply unifi configuration to unifi
  hosts: unifi
  gather_facts: yes

  tasks:
  - import_role:
      name: apt-upgrade
    tags:
      - apt-upgrade
