---

# If this is the first runthrough, the cert directory doesn't exist yet.
- name: check if live cert directory exists
  stat: path=/etc/letsencrypt/live/{{ hostname }}/fullchain.pem
  register: cert_file

# Note: Add "--test-cert" to this command to test using Let's Encrypt staging server instead (no rate limit).
- name: get initial letsencrypt certificate for {{ hostname }}
  command: certbot certonly -n -d {{ hostname }} -m {{ letsencrypt_email }} --agree-tos --webroot -w /var/www/letsencrypt
  when: cert_file.stat.exists == False
  notify: restart nginx
