---

- import_tasks: configure-firewall.yml
  tags:
    - configure-firewall

- import_tasks: install-controller.yml
  tags:
    - install-controller

- import_tasks: configure-unifi-controller-nginx.yml
  tags:
    - configure-unifi-controller-nginx
