---

- name: restart nginx
  service:
    name: nginx
    state: restarted
  notify:
    - wait for nginx to be healthy

- name: wait for nginx to be healthy
  wait_for:
    timeout: 60
    port: 80

# Must be run once, manually, after doing the initial certificate request
- name: run letsencrypt deploy hook
  command: /etc/letsencrypt/renewal-hooks/deploy/nginx_letsencrypt_deploy_hook.sh
